# Generated by Django 5.1.4 on 2024-12-21 23:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cualquiera', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada')], default='PENDING', max_length=12)),
                ('fecha_ven', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_frontpage', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('category', models.ManyToManyField(blank=True, to='tasks.category')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-post_date'],
            },
        ),
    ]
