# Generated by Django 5.1.4 on 2024-12-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_image_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_frontpage',
            field=models.ImageField(blank=True, default='tasks/images/image_default.jpg', null=True, upload_to='tasks/images/'),
        ),
    ]
