# Generated by Django 5.1.4 on 2024-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_image_frontpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pending_tasks', 'Pendiente'), ('in_progress_tasks', 'En Progreso'), ('completed_tasks', 'Completada')], default='PENDING', max_length=50),
        ),
    ]
