# Generated by Django 5.1.4 on 2024-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_completed_alter_task_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pending_tasks', 'Pendiente'), ('in_progress_tasks', 'En Progreso'), ('completed_tasks', 'Completada')], default='pending_tasks', max_length=50),
        ),
    ]
